### ISSUE TITLE
Bump json-patch

### ISSUE THREAD

**Issue by jayvdb** [kstasik/schema-tools#74] opened 2023-03-02 19:08 UTC
We are currently using 0.2.7, and there are non-trivial breaking changes in the current version 0.3.0.

I didnt include it in https://github.com/kstasik/schema-tools/pull/70 as old json-patch isnt a cause for concern

**Comment by kudlatyamroth** [comment] 2023-12-15 13:43
duplicate of https://github.com/kstasik/schema-tools/issues/93

**Closed by kudlatyamroth** 2023-12-15 13:43 UTC
